#FROM node:14.21-bullseye
FROM node:16.18-bullseye

ADD package.json package-lock.json /opt/build/

RUN cd /opt/build && npm install

ADD . /opt/build

WORKDIR /opt/build

#RUN npm run build
#
#RUN npm run pack

CMD ["/bin/bash"]
